baseURL = "https://joelclermont.com"
languageCode = "en-US"
title = "Joel Clermont"
theme = "nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
# disqusShortname = "jclermont"

# Google Analytics UA number
# googleAnalytics = "UA-21763858-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[blackfriday]
hrefTargetBlank = true

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Blog"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Podcast"
  weight = 20
  identifier = "podcast"
  url = "https://show.nocompromises.io/"

[[menu.main]]
  name = "Contact"
  weight = 30
  identifier = "contact"
  url = "/contact"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Speaking"
  weight = 50
  identifier = "speaking"
  url = "/speaking/"

# Add your own params here
[params]
  author = "Joel Clermont"
  avatar = "/img/avatar.jpg"
  seotitle = "Joel Clermont | Milwaukee web developer"
  subtitle = ""
  description = "The personal site of Joel Clermont"
  paginate = 10

  # Choose your social networks
  # email = ""
  github = "joelclermont"
  twitter = "jclermont"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  msValidate = "22596E34341DD1D17D6022C44647E587"
