[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.55.6"

[[redirects]]
  from = "/2011/09/15/date-calculations-are-more-complex-than-you-think/"
  to = "/post/2011/09/14/date-calculations-are-more-complex-than-you-think/"

[[redirects]]
  from = "/tag/conference/"
  to = "/tags/conferences/"

[[redirects]]
  from = "/2011/08/17/the-importance-of-upgrading/"
  to = "/post/2011/08/17/the-importance-of-upgrading"

[[redirects]]
  from = "/2012/04/17/i-love-twitter-bootstrap"
  to = "/post/2012/04/17/i-love-twitter-bootstrap"

[[redirects]]
  from = "/2011/07/16/wordpress-plugin-for-contextual-dynamic-text/"
  to = "/post/2011/07/16/wordpress-plugin-for-contextual-dynamic-text"

[[redirects]]
  from = "/tag/security/"
  to = "/tags/security/"
