---
- hosts: all
  sudo: true
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: install curl
      apt: pkg=curl

    - stat: path=/etc/profile.d/rvm.sh
      register: rvm_folder

    - name: Install RVM
      shell: "curl -sSL https://get.rvm.io | bash"
      when: rvm_folder.stat.isdir is not defined
      sudo: no

    - name: Install ruby 1.9.3
      shell: "rvm install ruby-1.9.3-p547"
      when: rvm_folder.stat.isdir is defined
      sudo: no

    # - name: Install Bundler
    #   apt: pkg=bundler

    # - name: Install libgc
    #   apt: pkg=libgc-dev

    # - name: Install pkg-config
    #   apt: pkg=pkg-config

    # - name: Install Haskell
    #   apt: pkg=haskell-platform state=latest

    # - name: Install Haskell terminfo bindings
    #   apt: pkg=libghc-terminfo-dev

    # - name: Install GMP
    #   apt: pkg=libgmp3-dev state=latest

    # - name: Update Cabal
    #   command: /usr/bin/cabal update
    #   sudo: false

    # - name: Install Idris
    #   command: /usr/bin/cabal install idris
    #   sudo: false

    # - name: Make sure Cabal is in PATH
    #   lineinfile: dest=/etc/environment state=present backrefs=yes regexp='PATH=(["]*)((?!.*?~/.cabal/bin).*?)(["]*)$' line="PATH=\1\2:~/.cabal/bin\3"